@ECHO Off
SETLOCAL

IF %1x == x GoTo Help

SET VER=%1

SET ROOTDIR=%~dp0
SET BINDIR=%ROOTDIR%bin\Release\AnyCPU
SET TARGET=%BINDIR%\AppData-%VER%.msix

SET SCRATCH=%BINDIR%\msix
IF EXIST %SCRATCH% RD /s/q %SCRATCH%
MD %SCRATCH% 2>&1 >NUL
COPY %BINDIR%\* %SCRATCH%\*
COPY %ROOTDIR%\appxmanifest.xml %SCRATCH%\*
COPY %ROOTDIR%\LICENSE %SCRATCH%\*
COPY %ROOTDIR%\README.md %SCRATCH%\*
COPY %ROOTDIR%\README.html %SCRATCH%\*
COPY %ROOTDIR%\src\appdata-48x48.png %SCRATCH%\*
COPY %ROOTDIR%\src\appdata-100x100.png %SCRATCH%\*

SET MAKEAPPX=makeappx.exe
SET MAKEAPPX_OPTS=pack /v /o /d %SCRATCH% /p %TARGET%
ECHO %MAKEAPPX% %MAKEAPPX_OPTS%
%MAKEAPPX% %MAKEAPPX_OPTS%
IF ERRORLEVEL 1 GOTO TheEnd

GoTo TheEnd

:Help
ECHO Usage: MAKEMSIX version

:TheEnd
ENDLOCAL
