using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AppData
{
    class Win32Errors
    {
        public enum Severity
        {
            SEVERITY_SUCCESS = 0,
            SEVERITY_ERROR = 1
        }

        public enum Facility
        {
            FACILITY_AAF = 18,
            FACILITY_ACCELERATOR = 1536,
            FACILITY_ACS = 20,
            FACILITY_AUDCLNT = 2185,
            FACILITY_AUDIO = 102,
            FACILITY_AUDIOSTREAMING = 1094,
            FACILITY_BACKGROUNDCOPY = 32,
            FACILITY_BCD = 57,
            FACILITY_BLB = 120,
            FACILITY_BLBUI = 128,
            FACILITY_BLB_CLI = 121,
            FACILITY_BLUETOOTH_ATT = 101,
            FACILITY_CERT = 11,
            FACILITY_CMI = 54,
            FACILITY_COMPLUS = 17,
            FACILITY_CONFIGURATION = 33,
            FACILITY_CONTROL = 10,
            FACILITY_DAF = 100,
            FACILITY_DEBUGGERS = 176,
            FACILITY_DEFRAG = 2304,
            FACILITY_DEPLOYMENT_SERVICES_BINLSVC = 261,
            FACILITY_DEPLOYMENT_SERVICES_CONTENT_PROVIDER = 293,
            FACILITY_DEPLOYMENT_SERVICES_DRIVER_PROVISIONING = 278,
            FACILITY_DEPLOYMENT_SERVICES_IMAGING = 258,
            FACILITY_DEPLOYMENT_SERVICES_MANAGEMENT = 259,
            FACILITY_DEPLOYMENT_SERVICES_MULTICAST_CLIENT = 290,
            FACILITY_DEPLOYMENT_SERVICES_MULTICAST_SERVER = 289,
            FACILITY_DEPLOYMENT_SERVICES_PXE = 263,
            FACILITY_DEPLOYMENT_SERVICES_SERVER = 257,
            FACILITY_DEPLOYMENT_SERVICES_TFTP = 264,
            FACILITY_DEPLOYMENT_SERVICES_TRANSPORT_MANAGEMENT = 272,
            FACILITY_DEPLOYMENT_SERVICES_UTIL = 260,
            FACILITY_DIRECT2D = 2201,
            FACILITY_DIRECT3D10 = 2169,
            FACILITY_DIRECT3D11 = 2172,
            FACILITY_DIRECTMUSIC = 2168,
            FACILITY_DIRECTORYSERVICE = 37,
            FACILITY_DISPATCH = 2,
            FACILITY_DLS = 153,
            FACILITY_DMSERVER = 256,
            FACILITY_DPLAY = 21,
            FACILITY_DXGI = 2170,
            FACILITY_DXGI_DDI = 2171,
            FACILITY_EAP = 66,
            FACILITY_EAS = 85,
            FACILITY_FVE = 49,
            FACILITY_FWP = 50,
            FACILITY_GRAPHICS = 38,
            FACILITY_HTTP = 25,
            FACILITY_INPUT = 64,
            FACILITY_INTERNET = 12,
            FACILITY_ITF = 4,
            FACILITY_LEAP = 2184,
            FACILITY_LINGUISTIC_SERVICES = 305,
            FACILITY_MBN = 84,
            FACILITY_MEDIASERVER = 13,
            FACILITY_METADIRECTORY = 35,
            FACILITY_MOBILE = 1793,
            FACILITY_MSMQ = 14,
            FACILITY_NAP = 39,
            FACILITY_NDIS = 52,
            FACILITY_NULL = 0,
            FACILITY_ONLINE_ID = 134,
            FACILITY_OPC = 81,
            FACILITY_P2P = 99,
            FACILITY_P2P_INT = 98,
            FACILITY_PARSE = 113,
            FACILITY_PIDGENX = 2561,
            FACILITY_PLA = 48,
            FACILITY_POWERSHELL = 84,
            FACILITY_RAS = 83,
            FACILITY_RESTORE = 256,
            FACILITY_RPC = 1,
            FACILITY_SCARD = 16,
            FACILITY_SCRIPT = 112,
            FACILITY_SDIAG = 60,
            FACILITY_SECURITY = 9,
            FACILITY_SETUPAPI = 15,
            FACILITY_SHELL = 39,
            FACILITY_SOS = 160,
            FACILITY_SPP = 256,
            FACILITY_SSPI = 9,
            FACILITY_STATE_MANAGEMENT = 34,
            FACILITY_STORAGE = 3,
            FACILITY_SXS = 23,
            FACILITY_TPM_SERVICES = 40,
            FACILITY_TPM_SOFTWARE = 41,
            FACILITY_UI = 42,
            FACILITY_UMI = 22,
            FACILITY_URT = 19,
            FACILITY_USERMODE_COMMONLOG = 26,
            FACILITY_USERMODE_FILTER_MANAGER = 31,
            FACILITY_USERMODE_HYPERVISOR = 53,
            FACILITY_USERMODE_SPACES = 231,
            FACILITY_USERMODE_VHD = 58,
            FACILITY_USERMODE_VIRTUALIZATION = 55,
            FACILITY_USERMODE_VOLMGR = 56,
            FACILITY_USERMODE_VOLSNAP = 130,
            FACILITY_USN = 129,
            FACILITY_VISUALCPP = 109,
            FACILITY_WEB = 885,
            FACILITY_WEBSERVICES = 61,
            FACILITY_WEB_SOCKET = 886,
            FACILITY_WER = 27,
            FACILITY_WIA = 33,
            FACILITY_WIN32 = 7,
            FACILITY_WINCODEC_DWRITE_DWM = 2200,
            FACILITY_WINDOWS = 8,
            FACILITY_WINDOWSUPDATE = 36,
            FACILITY_WINDOWS_CE = 24,
            FACILITY_WINDOWS_DEFENDER = 80,
            FACILITY_WINDOWS_SETUP = 48,
            FACILITY_WINDOWS_STORE = 63,
            FACILITY_WINPE = 61,
            FACILITY_WINRM = 51,
            FACILITY_WMAAECMA = 1996,
            FACILITY_WPN = 62,
            FACILITY_WSBAPP = 122,
            FACILITY_WSB_ONLINE = 133,
            FACILITY_XAML = 43,
            FACILITY_XPS = 82
        }

        public static int MakeHResult(Severity severity, Facility facility, int code)
        {
            return (int)((((uint)severity) << 31) | (((uint)facility) << 16) | ((uint)code));
        }

        public static readonly int ERROR_OBJECT_NOT_FOUND = MakeHResult(Severity.SEVERITY_ERROR, Facility.FACILITY_WIN32, 0x10d8);
    }
}
